# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  telegraf-master-01:
    :hostname: "telegraf-master-01"
    :ip: "192.168.40.129"
    :ram: 2048
    :cpu: 2
    :box: "ubuntu/xenial64"
    :id: 10

:groups:
  telegraf-master-01:
    - telegraf-master-01
  servers:
    - telegraf-master-01
  telegraf_masters:
    - telegraf-master-01
